apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: prometheus-rulefiles
  name: prometheus-rules-catalog-prod
  namespace: monitoring
spec:
  groups:
  - name: application.rules
    rules:
    - alert: HighCatalogApiUsage
      annotations:
        message: 'Api usage is greater than 10.'
      expr: count_requests_total > 10
      for: 10s
      labels:
        severity: warning