apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: prometheus-rulefiles
    app: stakater
    kind: apps
    release: stakater-monitoring-po
  name: prometheus-rules-catalog-prod
  namespace: monitoring
spec:
  groups:
  - name: application.rules
    rules:
    - alert: HighCatalogProdApiUsage
      annotations:
        message: 'Api usage is greater than 10.'
      expr: count_requests_total{namespace="nordmart-prod-apps"} > 10
      for: 10s
      labels:
        kind: apps
        severity: warning
