---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-prod-inventory
  namespace: nordmart-prod-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-prod-inventory
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.5
  values:
    applicationName: "inventory"
    deployment:
      podLabels:
        app: inventory
      volumes: {}
      image:
        repository: docker-delivery.workshop.stakater.com:443/stakater/inventory
        tag: v0.0.5
      imagePullSecrets: "docker-registry-nexus-secret"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /healthCheck
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /healthCheck
            port: 8080
    service:
      annotations:
        config.xposer.stakater.com/Domain: workshop.stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-prod'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-prod.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
