---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-prod-review
  namespace: nordmart-prod-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-prod-review
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.12
  values:
    applicationName: "review"
    deployment:
      podLabels:
        app: review
      volumes: {}
      image:
        repository: docker-delivery.cp-stakater.com:443/stakater-lab/review
        tag: <add-tag-herer>
      imagePullSecrets: "docker-registry-nexus-secret"
      fluentdConfigAnnotations:  
          regex: /^(?<time>\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+)\\s*(?<level>\\S+) (?<pid>\\d+) --- \\[(?<thread>[\\s\\S]*?)\\] (?<class>\\S+)\\s*:\\s*(?<message>[\\s\\S]*?)(?=\\g<time>|\\Z)/
          regexFirstLine: /^\\d+(?:-\\d+){2}\\s+\\d+(?::\\d+){2}\\.\\d+/
          timeFormat: "%Y-%m-%d %H:%M:%S.%L"
      env:
      - name: DB_NAME
        value: "nordmartDB"
      - name: MONGO_HOST
        value: "mongodb-svc.nordmart-prod-apps.svc.cluster.local"

      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080

    service:
      ports:
      - port: 8080
        name: https
        targetPort: 8080
      additionalLabels:
        expose: "true"
      annotations:
        config.xposer.stakater.com/Domain: cp-stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-dev'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-dev.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
