apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-nexus-secret
  namespace: nordmart-prod-apps
spec:
  encryptedData:
    .dockercfg: AgCGVPvDs4GGIR1r2ecHyjlPj/69FkWypjpXfJlu2ySdad9nbUxGH3811YIWcr3OwWguSHyATzSiqj4xmAy2I5F09IpIrxcLHcJqwp+VsAeJ0oPHORmkQA5N2ORV/tKYvtVXFVIYBWATah3rNZWro+p5+cY4KNcyGNGwcYru9xmvJutZCYyMXMoxpgU4UJ0AJGfu6cro0lZ5g2ZH08/BHuc70hk48pIognTW10JoDN1/EEqxBXjdemnL51I96sLww8Ztscy9fijTuN0du1VTNzQHvnQ1dvjgfnihTjR+wrDpD4uAcwYd/CoVo8yTDbkE/DfUnjFhMdwT0BVoKsPqBz+lr2w1ewUlIwe/FCCw+T4mpMNU/PfK6BPunwaHOzbFIbCy0fet45OACBi+cSOqOxSqWeo7Jf4rVJOTDt3txfAqsOQ1PET2ts5UAhGBXNpUmypx3JO3obUNooJV4kWvQhBAeDR4EQekjQJ9GztNqlt47RXPg8h9FU+9eAcU8AA36815x94DAxh0WSRfyV6ceS/IvlFN0YK/3DeeKRIxxH1j5VsPYw4zobqIw1bAE13lpghOIJNquuCQFkV3ieHiEdUoGAO3qQVjQYxeWQDt4St0iaMYZhv5jA0QELHNcqmSIrW5UHIDgvDVTLofeF1RffWHXAUYao8X857KPGBUQ/NTVyyMPc+Nnxn2yzpIByo91ItHiLPo4ybX5NupugUhqpi1lJdjxU3zUGqNwZmmryCL17FLStmSPu34CUDbKKVmXxlbWSUMQeLSTRf2v5hj4iaQWGr3nUSFzfB9ZRM9QYAD5e8pVXRusb6r0uZKeSCczNRC2SNMCbrJ7BnxTXVZh/86lmO+GSIjIyfc3gnYBgjrcW/bu4OAWA33/BxNIu5i5O31Nvcw8E4pSbv8JcAA1oDwRz+DzelW0fu0vJI=
  template:
    metadata:
      name: docker-registry-nexus-secret
      namespace: nordmart-prod-apps
    type: kubernetes.io/dockercfg

