---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nordmart-prod-web
  namespace: nordmart-prod-apps
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.deployment: semver:~0.0.*
spec:
  releaseName: nordmart-prod-web
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: application
    version: 0.0.5
  values:
    applicationName: "web"
    deployment:
      podLabels:
        app: web
      image:
        repository: docker-release.workshop.stakater.com:443/stakater/web
        tag: v0.0.13
      imagePullSecrets: "docker-registry-nexus-secret"
      probes:
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 4200
      volumes: {}
      env:
      - name: PORT
        value: "4200"
      # - name: SSO_URL
      #   value: "https://keycloak.global.stakater.com"
      - name: SECURE_GW_ENDPOINT
        value: "https://gateway-prod.workshop.stakater.com"
    service:
      ports:
      - port: 4200
        name: web
        protocol: TCP
        targetPort: 4200
      annotations:
        config.xposer.stakater.com/Domain: workshop.stakater.com
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-prod'
        config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-prod.{{.Domain}}'
        config.xposer.stakater.com/TLS: 'true'
        config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: external-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: locally
    rbac:
      create: false
      serviceAccount:
        name: default
    configMap:
      enabled: false
